Factory bot addition
ramasoftdev/twitter-clone pull request #34
Opened 2021-03-11 15:49 UTC by ramasoftdev

This PR adds FactoryBot to the project.
 
## Description: Why did you change/implement that?
To enable and use FactoryBot on TDDs

## Testing: Help me how can I test or look at the changes?
Checking out the Gemfile.lock and Gemfile

2021-03-12 20:55 UTC, juankhazbun requested changes

2021-03-13 02:10 UTC, ramasoftdev commented on app/controllers/application_controller.rb
> +  def following_count
Los pasé a un helper, ah si toma el current_user; no hay que pasarlo.

2021-03-15 23:31 UTC, juankhazbun requested changes
Asegurate de quitar los comentarios innecesarios del codigo.
Asegurate de usar los shoulda-matchers en las validaciones de los modelos.
Asegurate de preferir la sintaxis `:` a `=>`.

2021-03-15 23:31 UTC, juankhazbun commented on app/models/user.rb
> +  has_many :follower, :class_name => 'Follow', foreign_key: 'following_user_id'
Sintaxis: Cambiar de `=>` a `:`

2021-03-15 23:31 UTC, juankhazbun commented on app/views/home/index.html.erb
> +                        <% user = @users_tweets.select{|user| user.id == tweet.user_id}.first %>
Asegurate de verificar rubocop. 
```suggestion
                        <% user = @users_tweets.select { |user| user.id == tweet.user_id }.first %>
```

2021-03-15 23:31 UTC, juankhazbun commented on app/views/home/index.html.erb
> +                        <% user = @users_tweets.select{|user| user.id == tweet.user_id}.first %>
Que exactamente buscar hacer en esta linea?

2021-03-15 23:31 UTC, juankhazbun commented on spec/models/tweet_spec.rb
> +  describe 'Validations' do
No estoy seguro si en este PR o en otro pero no estas usando shoulda matchers para validar los modelos.
```suggestion
  it { is_expected.to validate_presence_of(:user_id) }
  it { is_expected.to validate_presence_of(:twett_content) }
```

2021-03-15 23:31 UTC, juankhazbun commented on spec/models/user_spec.rb
> +    it 'is not valid without an username' do
Usa shoulda matcher:
```suggestion
    it { is_expected.to validate_presence_of(:username) }
    it { is_expected.to validate_uniqueness_of(:username) }
```

2021-03-15 23:32 UTC, juankhazbun commented
@ramasoftdev para poder mergear este PR tienes que sacar el codigo que pertenece al PR #35

2021-03-16 00:35 UTC, ramasoftdev commented on app/views/home/index.html.erb
> +                        <% user = @users_tweets.select{|user| user.id == tweet.user_id}.first %>
Esto lo cambié en el PR 37. Ya que se hace un includes de user por cada tweet.
Lo que hacia es que una vez en el controlador obtenía los tweets, extraía los usuarios de esos tweets y con ellos creaba un array de usuarios, pero ya eso se quito.

2021-03-16 00:35 UTC, ramasoftdev commented on app/models/user.rb
> +  has_many :follower, :class_name => 'Follow', foreign_key: 'following_user_id'
En el PR 37 se hace cambio de esa linea.

2021-03-16 00:35 UTC, ramasoftdev commented on app/views/layouts/_navbar.html.erb
> +            <a class="nav-link" href="<%= follower_users_path %>">Followers <span class="badge badge-secondary"><%= current_user.following_users.count %></span></a>
Si. El PR 37 se mueve a helpers y en el PR 39 se hacen los test.

2021-03-16 00:35 UTC, ramasoftdev commented on app/controllers/home_controller.rb
> +        # p "Entre aqui 3"
Quitado en el PR 37, que se implementa rubocop.

2021-03-16 00:35 UTC, ramasoftdev commented on spec/models/tweet_spec.rb
> +  describe 'Validations' do
Si, en efecto shoulda matchers se usa en el PR 36.

2021-03-16 00:36 UTC, ramasoftdev commented on spec/models/user_spec.rb
> +    it 'is not valid without an username' do
Si, en efecto shoulda matchers se usa en el PR 36.

2021-03-17 13:28 UTC, juankhazbun approved these changes
LGTM 🚢

2021-03-17 15:05 UTC, merged